//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tip() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Repository.Tip", typeof(Tip).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 提交資訊不完整！ 的當地語系化字串。
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除數據失敗！ 的當地語系化字串。
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該使用者不可修改! 的當地語系化字串。
        /// </summary>
        internal static string GodUserInvaild {
            get {
                return ResourceManager.GetString("GodUserInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 插入數據庫失敗! 的當地語系化字串。
        /// </summary>
        internal static string InserError {
            get {
                return ResourceManager.GetString("InserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已存在! 的當地語系化字串。
        /// </summary>
        internal static string IsExist {
            get {
                return ResourceManager.GetString("IsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選單目前最多支援2級！ 的當地語系化字串。
        /// </summary>
        internal static string MenuOverFlow {
            get {
                return ResourceManager.GetString("MenuOverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非法呼叫! 的當地語系化字串。
        /// </summary>
        internal static string RequestInvaild {
            get {
                return ResourceManager.GetString("RequestInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該角色名稱已存在! 的當地語系化字串。
        /// </summary>
        internal static string RoleNameIsExists {
            get {
                return ResourceManager.GetString("RoleNameIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該角色不存在! 的當地語系化字串。
        /// </summary>
        internal static string RoleNotExist {
            get {
                return ResourceManager.GetString("RoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 意料外錯誤! 的當地語系化字串。
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新數據庫失敗! 的當地語系化字串。
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
    }
}
